config/routes.rb
Rails.application.routes.draw do
  root to: 'plays#top'
  
  get '/plays/1', to: 'plays#plays_1'
  get '/plays/2', to: 'plays#plays_2'
  get '/plays/3', to: 'plays#plays_3'
  get '/plays/4', to: 'plays#plays_4'
  get '/plays/5', to: 'plays#plays_5'
  get '/plays/win', to: 'plays#win'
  get '/plays/lose', to: 'plays#lose'
  get '/plays/timeout', to: 'plays#timeout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def top ;end
  
  def plays_1 ;end

  def plays_2 ;end

  def plays_3 ;end

  def plays_4 ;end

  def plays_5 ;end

  def win
    redirect_to root_path, success: '最強だ！ あなたはどんな速いサイトにも対応できるでしょう。'
  end

  def lose
    redirect_to root_path, danger: 'そのボタン押したらダメですやーん。'
  end

  def timeout
    redirect_to root_path, warning: '時間ぎれ！ 油断したな！！'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'Navbar絶対押させない',
      title: '',
      reverse: true,
      separator: '|',
      description: 'ボタンを押せたらあなたの勝ちです',
      keywords: '',
      canonical: request.original_url,
      noindex: ! Rails.env.production?,
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('icon.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'Navbar絶対押させない',
        title: 'Navbar絶対押させない',
        description: 'ボタンを押せたらあなたの勝ちです', 
        type: 'website',
        url: request.original_url,
        image: image_url('icon.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: '',
        site: '',
      },
      fb: {
        app_id: ''
      }
    }
  end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <title>NavbarGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/plays/plays_1.html.erb
<div id="particles-js"></div>

<div class="plays-1-page">
  <div class="container-fluid">

    <div class="nav-zone">
      <%= link_to plays_2_path, class: 'js-btn-1', "data-turbolinks": false do %>
        <button type="button" class="btn btn-primary btn-lg">押せ！</button>
      <% end %>
    </div>

    <h1 class="level text-white text-center">Level.1<h1>

  </div>
</div>









  

app/views/plays/plays_2.html.erb
<div id="particles-js"></div>

<div class="plays-2-page">
  <div class="container-fluid">
    
    <div class="nav-zone">
      <%= link_to plays_3_path, class: 'js-btn-2', "data-turbolinks": false do %>
        <button type="button" class="btn btn-primary btn-lg">押せ！</button>
      <% end %>
    </div>

    <h1 class="level text-white text-center">Level.2<h1>

  </div>
</div>

app/views/plays/plays_3.html.erb
<div id="particles-js"></div>

<div class="plays-3-page">
  <div class="container-fluid">

    <div class="nav-zone">
      <%= link_to plays_4_path, class: 'js-btn-3', "data-turbolinks": false do %>
        <button type="button" class="btn btn-primary btn-lg">押せ！</button>
      <% end %>
    </div>

    <h1 class="level text-white text-center">Level.3<h1>

  </div>
</div >

app/views/plays/plays_4.html.erb
<div id="particles-js"></div>

<div class="plays-4-page">
  <div class="container-fluid">

      <div class="nav-zone nav-4">
        <%= link_to plays_5_path, class: 'js-btn-4', "data-turbolinks": false do %>
          <button type="button" class="btn btn-primary btn-lg">押せ！</button>
        <% end %>

        <%= link_to plays_lose_path, class: 'js-bad-btn-4-1', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押すな！</button>
        <% end %>

        <%= link_to plays_lose_path, class: 'js-bad-btn-4-2', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押すな！</button>
        <% end %>
      </div>

      <h1 class="level text-white text-center">Level.4<h1>

  </div>
<div>

app/views/plays/plays_5.html.erb
<div id="particles-js"></div>

<div class="plays-5-page">
  <div class="container-fluid">

      <div class="nav-zone">
        <%= link_to plays_win_path, class: 'js-btn-5', "data-turbolinks": false do %>
          <button type="button" class="btn btn-primary btn-lg">押せ！</button>
        <% end %>

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-1', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押せ！</button>
        <% end %>

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-2', "data-turbolinks": false do %>
          <button type="button" class="btn btn-primary btn-lg">押すな！</button>
        <% end %>

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-3', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押すな！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-4', "data-turbolinks": false do %>
          <button type="button" class="btn btn-primary btn-lg">押すな！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-5', "data-turbolinks": false do %>
          <button type="button" class="btn btn-success btn-lg">押せ！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-6', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押すな！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-7', "data-turbolinks": false do %>
          <button type="button" class="btn btn-success btn-lg">押すな！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-8', "data-turbolinks": false do %>
          <button type="button" class="btn btn-warning btn-lg">押すな！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-9', "data-turbolinks": false do %>
          <button type="button" class="btn btn-danger btn-lg">押せ！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-10', "data-turbolinks": false do %>
          <button type="button" class="btn btn-warning btn-lg">押せ！</button>
        <% end %> 

        <%= link_to plays_lose_path, class: 'js-bad-btn-5-11', "data-turbolinks": false do %>
          <button type="button" class="btn btn-primary btn-lg">押すな！</button>
        <% end %> 
      </div>

      <h1 class="level text-white text-center">Level.5<h1>

  </div>
<div>

app/views/plays/top.html.erb
<div id="particles-js"></div>

<div class="top-page">
  <div class="container-fluid">
  <div class="row">

    <div class="top-card col-8">
      <h1 class="top-title text-center">Navbar絶対押させない。</h1>
      <p class="top-introduction text-center">
        制限時間内に<button type="button" class="btn btn-primary btn-sm">押せ！</button>を押すだけの超簡単ゲームです.<br>
        レベルは１から５までです.<br>
        <br>
        レベル５以外は全てウォーミングアップです.
      </p>

      <ul class="list-group list-group-horizontal-lg text-center">
        <li class="list-group-item flex-fill">
          <%= link_to 'Lv.1', plays_1_path, "data-turbolinks": false %>
        </li>

        <li class="list-group-item flex-fill">
          <%= link_to 'Lv.2', plays_2_path, "data-turbolinks": false %> 
        </li>

        <li class="list-group-item flex-fill">
          <%= link_to 'Lv.3', plays_3_path, "data-turbolinks": false %>
        </li>

        <li class="list-group-item flex-fill">
          <%= link_to 'Lv.4', plays_4_path, "data-turbolinks": false %>
        </li>

        <li class="list-group-item flex-fill">
          <%= link_to 'Lv.5', plays_5_path, "data-turbolinks": false %>
        </li>
      </ul>

      <p class="text-white text-center sorry">※ デザインがGoogle拡張機能 'DARK READER' に対応してません。ほんまにすいません。</p>
      
    </div>
    
  </div>
  </div>
</div>

 

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
<% end %>